spring.application.name=nextread

# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET}
jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:30}


# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# GEMINI
# ===============================

google.ai.api-key=${GOOGLE_API_KEY}
google.ai.model=gemini-2.5-flash